[build-system]
requires=["setuptools >= 77.0.3"]
build-backend="setuptools.build_meta"

[project]
version="0.6"
name="insitu_spex"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "lmfit",
    "emcee",
    "numdifftools",
    "tqdm",
    "solo-epd-loader",
    "sunpy",
    "sunpy-soar",
    "astropy",
    "spacepy",
]
[project.scripts]
inspex="INSPEX:fitting_gui"
instrument_choice="INSPEX:instrument_choice"
time_rng_select="INSPEX:time_rng_select"