[build-system]
requires=["setuptools >= 77.0.3"]
build-backend="setuptools.build_meta"

[project]
version="0.22"
name="insitu_spex"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "lmfit",
    "emcee",
    "numdifftools",
    "tqdm",
    "solo-epd-loader",
    "sunpy",
    "sunpy-soar",
    "astropy",
    "spacepy",
]

[project.scripts]
inspex="insitu_spex:instrument_choice"